---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-nginx
  labels:
    app: test-nginx
spec:
  progressDeadlineSeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: test-nginx
  template:
    metadata:
      labels:
        app: test-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:stable
          command: ["/bin/sh", "-c"]
          args:
            - sleep 180 && nginx -g 'daemon off;'
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 0
            periodSeconds: 3
            failureThreshold: 10
---
apiVersion: v1
kind: Service
metadata:
  name: test-nginx-svc
spec:
  type: ClusterIP
  selector:
    app: test-nginx
  ports:
    - port: 80
      targetPort: 80